CREATE TABLE IF NOT EXISTS items_bought
(
  id        SERIAL PRIMARY KEY,
  user_id   INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  item_id   INTEGER NOT NULL REFERENCES items (id) ON DELETE CASCADE
);